println "jenkinsfile start"
node{
try{    
checkout scm
} catch(e){ 
    getBinding().getVariables().each{ k, v ->
            println "${k}: ${v}"
          }
    println e
}
}
//gitlab.get_source_branch()
