
node{
  s3_download([path:'index.html', file:'index.html', force:true])
  s3_upload([path:'index2.html', file:'index.html', force:true])
  s3_delete([path:'index2.html'])
  s3_copy([fromPath:'index.html', toPath:'index3.html'])
}
